import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a formatted PDF report from the Strategic Map graph data.
 * @param {Object} graphData - The JSON representation of the graph.
 */
export const generatePDFReport = (graphData) => {
    if (!graphData || !graphData.nodes || !graphData.links) {
        console.error("Invalid graph data for PDF generation");
        return;
    }

    // Initialize document
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;

    // Helper Functions
    const addTitle = (text, y, size = 22, color = [33, 37, 41], align = 'center') => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(size);
        doc.setTextColor(color[0], color[1], color[2]);
        doc.text(text, align === 'center' ? pageWidth / 2 : margin, y, { align: align });
    };

    const addText = (text, x, y, options = {}) => {
        const { size = 11, font = "helvetica", style = "normal", color = [60, 64, 67], maxWidth = pageWidth - (margin * 2) } = options;
        doc.setFont(font, style);
        doc.setFontSize(size);
        doc.setTextColor(color[0], color[1], color[2]);
        const splitText = doc.splitTextToSize(text || '', maxWidth);
        doc.text(splitText, x, y);
        return splitText.length * (size * 0.35); // Return approximate height taken
    };

    // --- PAGE 1: Title Page ---
    const title = graphData.meta?.title || "Strategic Intelligence Report";
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    
    // Background flair
    doc.setFillColor(10, 10, 26);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
    
    addTitle(title.toUpperCase(), 120, 28, [255, 255, 255]);
    addTitle("Strategic Topology Generated by MindMe AI", 135, 12, [156, 163, 175]);
    addTitle(`Date: ${date}`, 150, 10, [156, 163, 175]);
    addTitle(`Nodes: ${graphData.nodes.length} | Connections: ${graphData.links.length}`, 160, 10, [156, 163, 175]);

    // --- Subsequent Pages Setup ---
    doc.addPage();
    doc.setFillColor(255, 255, 255); // Reset to white background for reading
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
    let currentY = margin;

    // --- Executive Summary ---
    const centerNode = graphData.nodes.find(n => n.type === 'central_hub' || n.type === 'macro') || graphData.nodes[0];
    
    if (centerNode) {
        addTitle("Executive Summary", currentY, 18, [31, 41, 55], 'left');
        currentY += 10;
        
        addText(`Core Focus: ${centerNode.label.toUpperCase()}`, margin, currentY, { style: 'bold' });
        currentY += 8;

        if (centerNode.content?.summary) {
            currentY += addText(centerNode.content.summary, margin, currentY);
            currentY += 10;
        }

        if (centerNode.content?.key_insight) {
            doc.setFillColor(243, 244, 246);
            const insightHeight = doc.splitTextToSize(`Insight: ${centerNode.content.key_insight}`, pageWidth - (margin * 2) - 10).length * 5;
            doc.rect(margin, currentY - 5, pageWidth - (margin * 2), insightHeight + 10, 'F');
            currentY += addText(`Insight: ${centerNode.content.key_insight}`, margin + 5, currentY, { style: 'italic', font: 'times' });
            currentY += 15;
        }
    }

    // --- Node Intelligence Breakdown ---
    doc.addPage();
    currentY = margin;
    addTitle("Comprehensive Node Intelligence", currentY, 18, [31, 41, 55], 'left');
    currentY += 15;

    // Group nodes (skip center node if already summarized)
    const otherNodes = graphData.nodes.filter(n => n.id !== centerNode?.id);
    
    otherNodes.forEach(node => {
        // Check page break
        if (currentY > pageHeight - 40) {
            doc.addPage();
            currentY = margin;
        }

        // Node Title & Type
        doc.setFillColor(229, 231, 235);
        doc.rect(margin, currentY - 6, pageWidth - (margin * 2), 10, 'F');
        addText(node.label.toUpperCase(), margin + 2, currentY, { style: 'bold', size: 12 });
        addText(`[${node.type.toUpperCase()}]`, pageWidth - margin - 30, currentY, { size: 9, color: [107, 114, 128] });
        currentY += 10;

        // Content
        if (node.content?.summary) {
            currentY += addText(node.content.summary, margin, currentY, { size: 10 });
            currentY += 5;
        }

        // Metrics
        if (node.content?.metrics && node.content.metrics.length > 0) {
            addText("Key Data Points:", margin, currentY, { style: 'bold', size: 10 });
            currentY += 6;
            node.content.metrics.forEach(m => {
                addText(`• ${m.label}: ${m.value}`, margin + 5, currentY, { size: 10, color: [16, 185, 129] }); // Emerald green
                currentY += 5;
            });
            currentY += 3;
        }

        // Sub-Topics & Challenges
        if (node.content?.challenges && node.content.challenges.length > 0) {
            addText("Challenges/Questions:", margin, currentY, { style: 'bold', size: 10 });
            currentY += 6;
            node.content.challenges.forEach(c => {
                currentY += addText(`• ${c}`, margin + 5, currentY, { size: 9 });
                currentY += 2;
            });
        }
        
        currentY += 8;
    });

    // --- Network Architecture Table ---
    doc.addPage();
    currentY = margin;
    addTitle("Network Architecture Topology", currentY, 18, [31, 41, 55], 'left');
    currentY += 10;

    const tableBody = graphData.links.map(link => {
        const sourceLabel = typeof link.source === 'object' ? link.source.label : (graphData.nodes.find(n => n.id === link.source)?.label || link.source);
        const targetLabel = typeof link.target === 'object' ? link.target.label : (graphData.nodes.find(n => n.id === link.target)?.label || link.target);
        
        return [
            sourceLabel,
            link.relation || 'Connects to',
            targetLabel,
            link.strength ? link.strength.toString() : '5'
        ];
    });

    autoTable(doc, {
        startY: currentY,
        head: [['Source Node', 'Relationship', 'Target Node', 'Gravity']],
        body: tableBody,
        theme: 'striped',
        headStyles: { fillColor: [74, 144, 217] },
        styles: { fontSize: 9, cellPadding: 3 },
        margin: { top: margin, left: margin, right: margin }
    });

    // Save PDF
    const safeTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    doc.save(`${safeTitle}_intelligence_report.pdf`);
};
